name: Serverless CICD

on:
  push:
    tags:
      - 'v*.*.*'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Convert Version Format
        id: convert_version
        run: |
          version="${{ steps.get_version.outputs.version }}"
          ver="${version//./_}"
          echo "Formatted Version: $ver"
          echo "::set-output name=formatted_version::$ver"

      - name: Install ESP-IDF and Build project
        uses: rmshub/esp-idf-action@v5
        with:
          esp_idf_version: v4.4.4
          esp_idf_target: esp32

      - name: Archive build output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./build/firmware_esp32_${{steps.convert_version.outputs.formatted_version}}.bin
